---
title: "Policy Effects for Income less than $35,000"
---

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(acs)
library(tidycensus)
library(tigris)
library(plotly)
library(shiny)
library(ggplot2)
library(viridis)
weights_geo_inc <- read.csv("img/weights_geo_inc.csv")
geo_census <- get_acs(geography = "tract",
                                  year = 2020,
                                  variables = c(Total = "B22003_001"
                                  ),
                                  state = 51, # VA
                                  county = 059,
                                  survey = "acs5",
                                  geometry = TRUE)
geo_census$GEOID <- as.numeric(geo_census$GEOID)
fairfax <- geo_census[, c(1, 2, 6)]
weights_geo_inc <- weights_geo_inc %>% left_join(fairfax, by = c("geoid"="GEOID"))
#View(weights_geo_inc)

names(weights_geo_inc)[names(weights_geo_inc)=='monthly_mean_COVID_benefit'] <- 'Monthly mean COVID benefit'
names(weights_geo_inc)[names(weights_geo_inc)=='monthly_mean_SNAP_benefit'] <- 'Monthly mean SNAP benefit'
```

## Distributions of COVID and SNAP Benefits

```{r, echo=FALSE, warning=FALSE}
# This version revised by Cesar
data_long <- weights_geo_inc %>% filter(income_cat == "Less than $35,000") %>% 
  pivot_longer(cols= c(`Monthly mean COVID benefit`, `Monthly mean SNAP benefit`), names_to = "Benefit_Type", values_to = "Dollars_Received")
#View(data_long)
mean_benefit_df <- data_long  %>% group_by(Benefit_Type) %>% dplyr::summarize(Mean=mean(Dollars_Received, na.rm = TRUE))
gg <- ggplot(data = data_long  ) +  
 geom_density(aes(x=Dollars_Received, color=Benefit_Type, fill=Benefit_Type, 
                  text = paste0(
                                'Benefit type: ', Benefit_Type)
                  
                  ), adjust=1.5, alpha=.4
              ) + 
  scale_fill_viridis( option = "D", discrete=TRUE, end=.6) +
  geom_vline(xintercept= unlist(mean_benefit_df[1,2]) , color="darkmagenta", linetype="dashed", linewidth=1) + 
  geom_vline(xintercept= unlist(mean_benefit_df[2,2]), color="darkgreen", linetype="dashed", linewidth=1) + 
  theme_bw() + 
  labs(title="Monthly SNAP Benefit for Households with Income less than $35,000", x="Monthly Average Benefit (Dollars)") 
plotly::ggplotly(gg, tooltip = c("x", "y", "text")) %>%  layout(legend = list(orientation = "h", 
                                     xanchor = "center",
                                     x = 0.5,
                                     y = -0.2) ) 
```


## Box plot

## SNAP eligibility vs SNAP $ change at household and person level for tracts/income levels

```{r, echo=FALSE}
dat = weights_geo_inc %>% filter(income_cat == "Less than $35,000")
g <- ggplot(dat, aes(x=SNAP_eligibility_proportion, y=`Monthly mean SNAP benefit` - `Monthly mean COVID benefit`, label = NAME, label2 = households_represented, label3 = average_hh_size, fill = income_cat)) + geom_point() + labs(title = "Loss of SNAP Benefits with New Policy per Tract", x = "Proportion of Households Eligible for SNAP", y = "Loss of Monthly SNAP Benefit (Dollars)") + scale_fill_manual(values="#232D4B")
gp <- ggplot(dat, aes(x=SNAP_eligibility_proportion, y=(`Monthly mean SNAP benefit` - `Monthly mean COVID benefit`)/average_hh_size, label = NAME, label2 = households_represented, fill = income_cat)) + geom_point() + labs(title = "Loss of SNAP Benefits with New Policy Per Person per Tract", x = "Proportion of Households Eligible for SNAP", y = "Loss of Monthly SNAP Benefit (Dollars) / Average Household Size") + scale_fill_manual(values="#232D4B")
ggplotly(g)
ggplotly(gp)
```