---
#title: "At-Risk Tracts"
#subtitle: "Which tracts are at-risk?"
---

```{r, echo=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(acs)
library(tidycensus)
library(tigris)
library(plotly)
library(shiny)
library(ggplot2)
library(viridis)

weights_geo <- read.csv("img/weights_geo.csv")

#census_api_key( Sys.getenv("census_key") )
census_api_key("eba406410c653b81d6a795ac4e989221f7bdf302")

geo_census <- get_acs(geography = "tract",
                                  year = 2020,
                                  variables = c(Total = "B22003_001"
                                  ),
                                  state = 51, # VA
                                  county = 059,
                                  survey = "acs5",
                                  geometry = TRUE)

geo_census$GEOID <- as.numeric(geo_census$GEOID)
fairfax <- geo_census[, c(1, 2, 6)]

weights_geo <- weights_geo %>% left_join(fairfax, by = c("geoid"="GEOID"))

#View(weights_geo)_inc)
#pop <- sum(weights_geo$households_represented)
#prop <- weighted.mean(weights_geo$SNAP_eligibility_proportion, weights_geo$households_represented)
#pop * prop

```

## Average monthly benefit of SNAP in Fairfax County (2020)



```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(sf)
library(leaflet)
library(dplyr)
library(readr)

#format st
weights_geo <- st_as_sf(weights_geo, crs = 4326) # %>% filter(tot_hh > 10)

#palette colors
pal <- colorBin("viridis", weights_geo$monthly_mean_SNAP_benefit)

#map leaflet

leaflet(weights_geo , options = leafletOptions(attributionControl = FALSE)) %>%
  setView(lng = -77.2464825271027, lat = 38.84619925123701, zoom = 10) %>%  
  addTiles() %>%
  addScaleBar("bottomleft") %>%
  addControl("Average monthly benefit of SNAP", "topright") %>%
  addLegend("bottomright", pal, weights_geo$monthly_mean_SNAP_benefit, opacity = .7) %>%
  addPolygons(
    fillColor = pal(weights_geo$monthly_mean_SNAP_benefit), fillOpacity = .7, weight = 1, color = "#000",
    highlightOptions = highlightOptions(color = "#fff"),
    label = paste0(
      "Census tract: ", weights_geo$NAME, "<br/>",
      "Average monthly benefit of SNAP: $", round(weights_geo$monthly_mean_SNAP_benefit,2), "<br/>",
      "Average monthly benefit of SNAP-Covid: $", round(weights_geo$monthly_mean_COVID_benefit,2), "<br/>",
      "Mean income per month: $", round(weights_geo$monthly_mean_income,2) ,  "<br/>",
      "SNAP eligibility (%): ", round(weights_geo$SNAP_eligibility_proportion, 3)
    )     %>%
      lapply(htmltools::HTML)
  ) 

```

<br>
<br>

## SNAP Eligibility Proportion vs Monthly Mean SNAP Benefit per Household

```{r, echo=FALSE}
hp <- c(51059482206, 51059452301, 51059451501)
highlight_points <- weights_geo %>% filter(geoid %in% hp)
```

```{r, echo=FALSE}
gg_benefit_eligibility <- ggplot(weights_geo, aes(x=SNAP_eligibility_proportion, y=monthly_mean_SNAP_benefit, label = NAME, label2 = households_represented, label3 = average_hh_size)) + geom_point(color="#232D4B") + labs(title = "")
ggplotly(gg_benefit_eligibility)
```
<br>
<br>

*Notable Tracts of Concern: 4822.06, 4523.01, 4515.01

```{r, echo=FALSE}
gg_benefit_eligibility <- ggplot(weights_geo, aes(x=SNAP_eligibility_proportion, y=monthly_mean_SNAP_benefit / average_hh_size, label = NAME, label2 = households_represented)) + geom_point(color="#232D4B") + labs(title = "SNAP Eligibility Proportion vs Monthly Mean SNAP Benefit per Person", y = "Monthly Mean SNAP Benefit / Average Household Size") + geom_point(data=highlight_points, aes(x=SNAP_eligibility_proportion, y=monthly_mean_SNAP_benefit / average_hh_size), color="#F84C1E", size=2)
ggplotly(gg_benefit_eligibility)
```